declare prepare_single in global scope
When using --save_all, I got:
AttributeError: Can't pickle local object 'main.<locals>.prepare_single'

Which is due to multiprocessing being unable to pickle local functions. 
Adding global declaration is a quick and dirty fix, and solves the problem.